

clang++ -miphoneos-version-min=13.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include -F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/OpenGLES.framework -arch arm64  -D_GLIBCXX_USE_CXX11_ABI=1 -miphoneos-version-min=13.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include -F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/OpenGLES.framework -arch arm64  -D_GLIBCXX_USE_CXX11_ABI=1 -DGATTLIB_LOG_LEVEL=10 -Wfloat-conversion -Wdouble-promotion -Wpedantic -Wall -Wextra -g -O0 -std=c++17 -I./headers  ./functions/MLX90640_API.c -c -o ./functions/MLX90640_API.o

clang++ -miphoneos-version-min=13.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include -F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/OpenGLES.framework -arch arm64  -D_GLIBCXX_USE_CXX11_ABI=1 -miphoneos-version-min=13.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include -F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/OpenGLES.framework -arch arm64  -D_GLIBCXX_USE_CXX11_ABI=1 -DGATTLIB_LOG_LEVEL=10 -Wfloat-conversion -Wdouble-promotion -Wpedantic -Wall -Wextra -g -O0 -std=c++17 -I./headers  ./functions/MLX90640_BLEProxy.cpp -c -o ./functions/MLX90640_BLEProxy.o

clang++ -miphoneos-version-min=13.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include -F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/OpenGLES.framework -arch arm64  -D_GLIBCXX_USE_CXX11_ABI=1 -miphoneos-version-min=13.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include -F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/OpenGLES.framework -arch arm64  -D_GLIBCXX_USE_CXX11_ABI=1 -DGATTLIB_LOG_LEVEL=10 -Wfloat-conversion -Wdouble-promotion -Wpedantic -Wall -Wextra -g -O0 -std=c++17 -I./headers  ./functions/MLX90640_Test.c -c -o ./functions/MLX90640_Test.o

ar rcs MLX_lib.a ./functions/MLX90640_BLEProxy.o ./functions/MLX90640_API.o ./functions/MLX90640_Test.o 




